### ISSUE TITLE
Odds delay

### ISSUE THREAD

**Issue by w4rdy** [S1M0N38/soccerapi#10] opened 2020-07-04 21:41 UTC
Hi,

Firstly thank you for making this, it's proving very helpful to my project!

I was wondering how large the delay is between the api and the live bet365 odds, since I am receiving different odds to those on the website.

Thanks

**Comment by w4rdy** [comment] 2020-07-04 22:10
I'm also getting the following error when using the bet365api, the 888sport and unibet apis work perfectly:

File "C:\Users\Admin\Documents\Code\soccerapi-master\soccerapi\api\bet365\bet365.py", line 76, in _parse_odds
    key = self._guess_xor_key(values[0])

**Comment by S1M0N38** [comment] 2020-07-06 14:17
Regarding the delay of the odds I have no clue: they should be the latest odds available. However the odds are different (and sometime by quite a margin) if bet365.com is access from  different country.

The second issue that you are experiencing it's related to the way that data coming from bet356 are parsed. At every requests the api naively brute force the char that is used in the xor data obfuscation and then reverse the obfuscation. Probably they change something in the obfuscation procedure and now the whole method fail.

I'm currently not maintain this project but there is a [repo](https://github.com/Chiang97912/bet365.com) that is parsing bet365 data: take a look, could be a useful resource to fix this problem.

**Comment by w4rdy** [comment] 2020-07-07 12:14
Hi, thanks for the reply. I looked at the repo you linked and it looks like bet365 have changed the way they cipher their xor data, making it increasingly harder for applications like this to access their odds data.

**Comment by S1M0N38** [comment] 2020-08-10 15:42
Duplicate of #11

**Closed by S1M0N38** 2020-08-10 15:42 UTC
